#####  Author :Samir


In [2]:
print("First Day Of The Code")

First Day Of The Code


In [9]:
list=[1,2,3]
print(list[:]*2)

[1, 2, 3, 1, 2, 3]


In [24]:
def sum(*args):
    return [num * 2 for num in args]


In [26]:
sum(2,200)

[4, 400]

### Numpy

In [28]:
import numpy as np

In [44]:
x = np.array([1,2,3,4])
y= np.array([[2,1],[3,5]])
print(x.shape) # it will give dimention like matrix format
print(x.size) # Number element
print(y.shape)
print(x.size) # Number element

(4,)
4
(2, 2)
4


In [50]:
tmp=np.array([2,3,4])
x = np.zeros((2,3,4))
print(tmp)
print(x)

[2 3 4]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [59]:
tmp=np.array([[2,3,4],[1,2,3]])
print(tmp)
tmp1=tmp.ravel()
print(tmp1) ## convert into single array from 

[[2 3 4]
 [1 2 3]]
[2 3 4 1 2 3]


### PANDAS

In [127]:
import pandas as pd
import random

In [152]:
print(random.random())


0.9424502837770503


In [158]:
# using seed() to seed a random number 
random.seed(5) 
print (random.random()) 

0.6229016948897019


In [161]:
tmp=pd.read_html("https://www.w3schools.com/html/html_tables.asp")


In [165]:
type(tmp[0])

pandas.core.frame.DataFrame

### plotly for dynamic graph