In [2]:
import numpy as np
import sklearn 
X = np.arange(6).reshape(3, 2)

In [3]:
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(2)

In [8]:
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [12]:
poly = PolynomialFeatures(2,interaction_only=True)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.]])